### ISSUE TITLE
AttributeError: 'int' object has no attribute 'encode'

### ISSUE THREAD

**Issue by 1qa2ws3ed4rf1** [ITCraftDevelopmentTeam/OneDisc#38]
[2024-10-11 21:31:45][asyncio / ERROR]: Task exception was never retrieved
future: <Task finished name='Task-25' coro=<HttpPost.push_event() done, defined at D:\qbot\opensourcehere\OneDisc\network\v11\http_post.py:34> exception=AttributeError("'int' object has no attribute 'encode'")>
Traceback (most recent call last):
  File "D:\qbot\opensourcehere\OneDisc\network\v11\http_post.py", line 43, in push_event
    response = await client.post(
  File "D:\ANACONDA3\envs\OPEN\lib\site-packages\httpx\_client.py", line 1905, in post
    return await self.request(
  File "D:\ANACONDA3\envs\OPEN\lib\site-packages\httpx\_client.py", line 1572, in request
    request = self.build_request(
  File "D:\ANACONDA3\envs\OPEN\lib\site-packages\httpx\_client.py", line 347, in build_request
    headers = self._merge_headers(headers)
  File "D:\ANACONDA3\envs\OPEN\lib\site-packages\httpx\_client.py", line 410, in _merge_headers
    merged_headers.update(headers)
  File "D:\ANACONDA3\envs\OPEN\lib\site-packages\httpx\_models.py", line 203, in update
    headers = Headers(headers)
  File "D:\ANACONDA3\envs\OPEN\lib\site-packages\httpx\_models.py", line 74, in __init__
    self._list = [
  File "D:\ANACONDA3\envs\OPEN\lib\site-packages\httpx\_models.py", line 78, in <listcomp>
    normalize_header_value(v, encoding),
  File "D:\ANACONDA3\envs\OPEN\lib\site-packages\httpx\_utils.py", line 53, in normalize_header_value
    return value.encode(encoding or "ascii")
AttributeError: 'int' object has no attribute 'encode'

**Comment by 1qa2ws3ed4rf1** [comment]
im trying to fix

**Comment by 1qa2ws3ed4rf1** [comment]
bug in onebotv11

**Comment by 1qa2ws3ed4rf1** [comment]
确认了 self_id的问题 normalize_header_value 1294161312430952459

**Comment by 1qa2ws3ed4rf1** [comment]
![image](https://github.com/user-attachments/assets/80543ab5-303d-417c-9c6a-1e6770d3c79c)

**Comment by 1qa2ws3ed4rf1** [comment]
我的建议是 str()

**Comment by 1qa2ws3ed4rf1** [comment]
如图
![image](https://github.com/user-attachments/assets/85db96a1-d41d-4a58-b0cd-025b2a51110c)

**Comment by 1qa2ws3ed4rf1** [comment]
File "d:\qbot\opensourcehere\OneDisc\network\v11\http_post.py"

**Comment by 1qa2ws3ed4rf1** [comment]
no use

**Comment by 1qa2ws3ed4rf1** [comment]
emm bug好像好了（）

**Comment by 1qa2ws3ed4rf1** [comment]
解决方案：在OneDisc\network\v11\http_post.py def get_headers 修改 headers = ..... 为headers = {"Content-Type": "application/json","X-Self-ID": str(client.user.id),  # type: ignore
}

**Comment by 1qa2ws3ed4rf1** [comment]
可能解决

**Comment by 1qa2ws3ed4rf1** [comment]
修改：新增
![image](https://github.com/user-attachments/assets/127f48a7-ff14-4ceb-9cd1-7c9a59f0877b)
以修复 timeout

**Comment by 1qa2ws3ed4rf1** [comment]
修改
![image](https://github.com/user-attachments/assets/86398088-e61c-49f5-b36e-26f0f71e78a2)
修复 timeout

**Comment by 1qa2ws3ed4rf1** [comment]
修改
![image](https://github.com/user-attachments/assets/09d93bc3-a062-4293-861a-765aff585707)
修复 AttributeError: 'int' object has no attribute 'encode' 尝试提交pull中
